### ISSUE TITLE
Allow to switch the icon to code-server icon

### ISSUE THREAD

**Issue by krassowski** [betatim/vscode-binder#60]
Currently the VS Code icon is used even when code-server is run. This is problematic because the Visual Studio Code icon is a Microsoft trademark and should not be used to represent products other than VS Code as per https://code.visualstudio.com/brand

Proposed solution:
- ship the code-server icon (https://github.com/coder/code-server/blob/main/src/browser/media/favicon.svg) as well
- allow to switch the icon based on an environment variable config

Any thoughts/counter ideas before I open a PR?

**Comment by benz0li** [comment]
Better use https://github.com/coder/code-server/blob/f15580b28ae021b549a723847497d6f8252b3eb2/src/browser/media/favicon-dark-support.svg

---

Because of https://bugs.webkit.org/show_bug.cgi?id=199134, this does not (yet) work with Safari, though.

Therefore, I created https://github.com/b-data/jupyterlab-python-docker-stack/blob/42b36973157f29ec867a9489aa9c20e387873f60/base/assets/opt/code-server/code-server.svg

**Comment by krassowski** [comment]
Good point on dark/light. `prefers-color-scheme` does not reflect the Jupyter theme (the browser/system may be set to dark but user may be using light theme). Instead we can add `jp-icon0` class which will automatically swap the fill between black and white depending on theme 

https://jupyterlab.readthedocs.io/en/latest/api/modules/ui_components.html#md:sync-icon-color-to-jupyterlab-theme
